import Foundation

/// Deterministic voxel models generated by evaluating formulas at cell centers, from 16 cells to 256 cells
/// on each axis. Each model fills exactly its size, and generation allocates no denser buffer than that model.
public enum SculptureMathExamples {
    /// The voxel rungs of the ladder, keyed by their axis size in cells.
    public enum Model: Int, CaseIterable, Sendable {
        /// Concentric sine ripples filled to the floor, banded by height.
        case ripple = 16
        /// A tilted torus with twisted angular stripes.
        case torus = 32
        /// A gyroid shell clipped to a sphere, banded by height.
        case gyroid = 64
        /// A planet whose radius follows spherical harmonics, with an ocean, beaches and snow.
        case harmonicSphere = 128
        /// A layered sine terrain with a sea, snow and wavy strata.
        case terrain = 256

        /// Cells on every axis.
        public var dimension: Int { rawValue }

        /// Stable gallery identity.
        public var id: String {
            switch self {
            case .ripple: "math-ripple-16"
            case .torus: "math-torus-32"
            case .gyroid: "math-gyroid-64"
            case .harmonicSphere: "math-harmonic-sphere-128"
            case .terrain: "math-terrain-256"
            }
        }

        /// Sculpture and gallery title.
        public var title: String {
            switch self {
            case .ripple: "Sine ripple"
            case .torus: "Striped torus"
            case .gyroid: "Gyroid shell"
            case .harmonicSphere: "Harmonic planet"
            case .terrain: "Layered sine terrain"
            }
        }

        /// One-line gallery description.
        public var summary: String {
            switch self {
            case .ripple: "Concentric cosine ripples fade from the center, banded by height."
            case .torus: "A tilted ring wrapped in twisted angular stripes."
            case .gyroid: "A triply periodic minimal surface carved into a ball."
            case .harmonicSphere: "Spherical harmonics raise continents above an ocean, with a hot core."
            case .terrain: "Summed sines make hills, lakes and snow over wavy rock strata."
            }
        }

        /// The generating formula in cell-center coordinates from the volume's corner, Y measured upward.
        /// Every centering offset is written out, so the formula alone reproduces the occupied cells.
        public var formula: String {
            switch self {
            case .ripple:
                "fill y <= 7.5 + 5.5 cos(1.15 r) exp(-0.07 r), r = hypot(x - 8, z - 8); band = floor(y / 3.2)"
            case .torus:
                "(hypot(x - 16, z') - 10)^2 + y'^2 <= 4.6^2, (y', z') = (y - 16, z - 16) rotated -0.45 rad "
                    + "about X; stripe = floor((12 theta + 3 phi) / 2 pi) mod 3"
            case .gyroid:
                "|sin X cos Y + sin Y cos Z + sin Z cos X| < 0.25, X = 2 pi x / 32, inside radius 31.5 of "
                    + "(32, 32, 32); band = floor(6 y / 64)"
            case .harmonicSphere:
                "r <= 46 + 16 (0.5 (nx^4 - 6 nx^2 nz^2 + nz^4) + 0.15 (5 ny^3 - 3 ny) + 1.82 nx ny nz), "
                    + "p = (x - 64, y - 64, z - 64), r = |p|, n = p / r; ocean to r = 47; altitude bands every "
                    + "2 cells; core and mantle by radius"
            case .terrain:
                "h = 100 + 40 sin(x / 41 + 0.3) cos(z / 53) + 22 sin((x + 2z) / 67) + 9 sin(x / 13) sin(z / 17); "
                    + "sea 80, snow 150, strata = floor((y + 5 sin(x / 29) + 4 cos(z / 23)) / 8)"
            }
        }
    }

    // MARK: - Public Methods

    /// Generates one voxel rung, checking cancellation before every layer.
    /// - Parameters:
    ///   - model: The rung to generate.
    ///   - progress: Receives the completed fraction, from above zero to one.
    /// - Returns: A sculpture exactly `model.dimension` cells on every axis.
    public static func sculpture(
        _ model: Model,
        progress: @Sendable (Double) async -> Void = { _ in }
    ) async throws -> Sculpture {
        SculptureGenerationProbe.record(model.id)
        try Task.checkCancellation()
        let size = model.dimension
        var layers: [[UInt8]] = []
        layers.reserveCapacity(size)
        for z in 0..<size {
            try Task.checkCancellation()
            let layer: [UInt8]
            switch model {
            case .ripple: layer = MathFields.ripple(z: z)
            case .torus: layer = MathFields.torus(z: z)
            case .gyroid: layer = MathFields.gyroid(z: z)
            case .harmonicSphere: layer = MathFields.harmonicSphere(z: z)
            case .terrain: layer = MathFields.terrain(z: z)
            }
            layers.append(layer)
            await progress(Double(z + 1) / Double(size + 1))
        }
        try Task.checkCancellation()
        let sculpture = try Sculpture(title: model.title, width: size, height: size, layers: layers)
        try Task.checkCancellation()
        await progress(1)
        return sculpture
    }
}

// MARK: - Materials

/// Palette bytes chosen for their distinct cube-view colors.
private enum MathGlyph {
    static let mint: UInt8 = 35
    static let violet: UInt8 = 64
    static let amber: UInt8 = 42
    static let blue: UInt8 = 43
    static let green: UInt8 = 111
    static let coral: UInt8 = 120
    static let fern: UInt8 = 58
    static let sand: UInt8 = 61
    static let cyan: UInt8 = 45
    static let strata: [UInt8] = [violet, coral, amber, sand]
}

/// Shared surface, soil, strata and water banding for the layered sine terrain.
private struct TerrainRules {
    let seaLevel: Double
    let snowLine: Double
    let beach: Double
    let strataThickness: Double

    /// Classifies the cell centered at upward `height` in a column whose surface is at `surface`.
    func glyph(height: Double, surface: Double, strataOffset: Double) -> UInt8 {
        guard height <= surface else { return height <= seaLevel ? MathGlyph.blue : Sculpture.empty }
        let depth = surface - height
        let shore = surface < seaLevel + beach
        if depth < 1 {
            if surface >= snowLine { return MathGlyph.mint }
            return shore ? MathGlyph.sand : MathGlyph.green
        }
        if depth < 4 { return shore ? MathGlyph.sand : MathGlyph.fern }
        let band = Int(((height + strataOffset) / strataThickness).rounded(.down))
        return MathGlyph.strata[((band % 4) + 4) % 4]
    }
}

// MARK: - Voxel Fields

/// Per-layer evaluation of each voxel rung. Document Y grows downward, so each field converts to upward height.
private enum MathFields {
    static func ripple(z: Int) -> [UInt8] {
        let size = 16
        let bands = [MathGlyph.violet, MathGlyph.blue, MathGlyph.green, MathGlyph.amber, MathGlyph.coral]
        var cells = [UInt8](repeating: Sculpture.empty, count: size * size)
        let w = Double(z) + 0.5 - 8
        for x in 0..<size {
            let u = Double(x) + 0.5 - 8
            let r = (u * u + w * w).squareRoot()
            let surface = 7.5 + 5.5 * cos(1.15 * r) * exp(-0.07 * r)
            for y in 0..<size {
                let height = Double(size - y) - 0.5
                guard height <= surface else { continue }
                cells[y * size + x] = bands[min(bands.count - 1, Int(height / 3.2))]
            }
        }
        return cells
    }

    static func torus(z: Int) -> [UInt8] {
        let size = 32
        // Tilting toward the default camera keeps the open center visible.
        let tilt = -0.45
        // Twelve stripes and a three-stripe twist are multiples of three colors, so neither angle wraps to a seam.
        let stripes = [MathGlyph.coral, MathGlyph.amber, MathGlyph.violet]
        var cells = [UInt8](repeating: Sculpture.empty, count: size * size)
        let pz = Double(z) + 0.5 - 16
        for y in 0..<size {
            let py = Double(size - y) - 0.5 - 16
            let tiltedY = py * cos(tilt) - pz * sin(tilt)
            let tiltedZ = py * sin(tilt) + pz * cos(tilt)
            for x in 0..<size {
                let px = Double(x) + 0.5 - 16
                let ring = (px * px + tiltedZ * tiltedZ).squareRoot() - 10
                guard ring * ring + tiltedY * tiltedY <= 4.6 * 4.6 else { continue }
                let theta = atan2(tiltedZ, px)
                let phi = atan2(tiltedY, ring)
                let stripe = Int(((12 * theta + 3 * phi) / (2 * Double.pi)).rounded(.down))
                cells[y * size + x] = stripes[((stripe % 3) + 3) % 3]
            }
        }
        return cells
    }

    static func gyroid(z: Int) -> [UInt8] {
        let size = 64
        let frequency = 2 * Double.pi / 32
        let bands = [
            MathGlyph.violet, MathGlyph.blue, MathGlyph.cyan, MathGlyph.green, MathGlyph.amber, MathGlyph.coral,
        ]
        var cells = [UInt8](repeating: Sculpture.empty, count: size * size)
        let cz = Double(z) + 0.5
        for y in 0..<size {
            let cy = Double(size - y) - 0.5
            for x in 0..<size {
                let cx = Double(x) + 0.5
                let dx = cx - 32
                let dy = cy - 32
                let dz = cz - 32
                let radius = (dx * dx + dy * dy + dz * dz).squareRoot()
                guard radius <= 31.5 else { continue }
                let (px, py, pz) = (cx * frequency, cy * frequency, cz * frequency)
                let field = sin(px) * cos(py) + sin(py) * cos(pz) + sin(pz) * cos(px)
                guard abs(field) < 0.25 else { continue }
                cells[y * size + x] = bands[min(bands.count - 1, Int(cy * 6 / 64))]
            }
        }
        return cells
    }

    static func harmonicSphere(z: Int) -> [UInt8] {
        let size = 128
        let seaLevel = 47.0
        var cells = [UInt8](repeating: Sculpture.empty, count: size * size)
        let dz = Double(z) + 0.5 - 64
        for y in 0..<size {
            let dy = Double(size - y) - 0.5 - 64
            for x in 0..<size {
                let dx = Double(x) + 0.5 - 64
                let distance = (dx * dx + dy * dy + dz * dz).squareRoot()
                guard distance <= 60 else { continue }
                let (nx, ny, nz) = (dx / distance, dy / distance, dz / distance)
                let sectoral = nx * nx * nx * nx - 6 * nx * nx * nz * nz + nz * nz * nz * nz
                let zonal = 0.5 * (5 * ny * ny * ny - 3 * ny)
                let tesseral = 5.2 * nx * ny * nz
                let surface = 46 + 16 * (0.5 * sectoral + 0.3 * zonal + 0.35 * tesseral)
                let glyph: UInt8
                if distance > surface {
                    guard distance <= seaLevel else { continue }
                    glyph = MathGlyph.blue
                } else {
                    let altitude = distance - seaLevel
                    switch distance {
                    case ..<16: glyph = MathGlyph.amber
                    case ..<30: glyph = MathGlyph.coral
                    default:
                        switch altitude {
                        case ..<1: glyph = MathGlyph.sand
                        case ..<3: glyph = MathGlyph.green
                        case ..<5: glyph = MathGlyph.fern
                        case ..<7: glyph = MathGlyph.violet
                        default: glyph = MathGlyph.mint
                        }
                    }
                }
                cells[y * size + x] = glyph
            }
        }
        return cells
    }

    static func terrain(z: Int) -> [UInt8] {
        let size = 256
        let rules = TerrainRules(seaLevel: 80, snowLine: 150, beach: 3, strataThickness: 8)
        var cells = [UInt8](repeating: Sculpture.empty, count: size * size)
        let cz = Double(z) + 0.5
        for x in 0..<size {
            let cx = Double(x) + 0.5
            let surface =
                100 + 40 * sin(cx / 41 + 0.3) * cos(cz / 53) + 22 * sin((cx + 2 * cz) / 67)
                + 9 * sin(cx / 13) * sin(cz / 17)
            let offset = 5 * sin(cx / 29) + 4 * cos(cz / 23)
            for y in 0..<size {
                cells[y * size + x] = rules.glyph(
                    height: Double(size - y) - 0.5,
                    surface: surface,
                    strataOffset: offset
                )
            }
        }
        return cells
    }
}
